CREATE TEMPORARY EXTERNAL TABLE hw2_test  
(id INT,
 f1 INT,f2 INT,f3 INT,f4 INT,f5 INT,f6 INT,f7 INT,f8 INT,f9 INT,f10 INT,f11 INT,f12 INT,f13 INT,
 cf1 STRING,cf2 STRING,cf3 STRING,cf4 STRING,cf5 STRING,cf6 STRING,cf7 STRING,cf8 STRING,cf9 STRING,cf10 STRING,
 cf11 STRING,cf12 STRING,cf13 STRING,cf14 STRING,cf15 STRING,cf16 STRING,cf17 STRING,cf18 STRING,cf19 STRING,cf20 STRING,
 cf21 STRING,cf22 STRING,cf23 STRING,cf24 STRING,cf25 STRING,cf26 STRING,
 day_number STRING
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/datasets/criteo_test_large_features' 
TBLPROPERTIES ("skip.header.line.count"="1");
